#pragma once
#include "Engine/Assets/AssetManager.h"
#include "Engine/Assets/ITextureImporter.h"
#include "Engine/Assets/IModelImporter.h"
#include "Engine/Assets/ModelCreateInfo.h"
#include "Engine/Assets/VertexFormat.h"

#include "Engine/Assets/AssetImporters/FBXImporter.h"
#include "Engine/Assets/AssetImporters/ModelImporter.h"
#include "Engine/Assets/AssetImporters/OBJImporter.h"
#include "Engine/Assets/AssetImporters/TextureImporterBase.h"
#include "Engine/Assets/AssetImporters/TextureImporterDDS.h"

#include "Engine/Core/ObjectClass.h"
#include "Engine/Core/Object.h"

#include "Engine/Debug/InputDebugInputHandler.h"

#include "Engine/Resources/Material.h"
#include "Engine/Resources/Model.h"
#include "Engine/Resources/Resource.h"
#include "Engine/Resources/Texture.h"

#include "Engine/EngineUI/Editor/EditorFooterWidget.h"
#include "Engine/EngineUI/Editor/EditorContentBrowserWidget.h"
#include "Engine/EngineUI/Editor/EditorDockspaceWidget.h"
#include "Engine/EngineUI/Editor/EditorHelpers.h"
#include "Engine/EngineUI/Editor/EditorOutputLogWidget.h"
#include "Engine/EngineUI/Editor/EditorPropertiesWidget.h"
#include "Engine/EngineUI/Editor/EditorSceneHierarchyWidget.h"
#include "Engine/EngineUI/Editor/EditorViewportWidget.h"
#include "Engine/EngineUI/Runtime/RuntimeConsoleWidget.h"
#include "Engine/EngineUI/Editor/EditorFrameProfilerWidget.h"

#include "Engine/World/Actors/Actor.h"
#include "Engine/World/Actors/CameraActor.h"
#include "Engine/World/Actors/DirectionalLightActor.h"
#include "Engine/World/Actors/LightProbeActor.h"
#include "Engine/World/Actors/PlayerController.h"
#include "Engine/World/Actors/PlayerInput.h"
#include "Engine/World/Actors/PointLightActor.h"
#include "Engine/World/Actors/SkyLightActor.h"
#include "Engine/World/Actors/SpotLightActor.h"

#include "Engine/World/Components/ActorComponent.h"
#include "Engine/World/Components/CameraComponent.h"
#include "Engine/World/Components/DirectionalLightComponent.h"
#include "Engine/World/Components/InputComponent.h"
#include "Engine/World/Components/LightComponent.h"
#include "Engine/World/Components/LightProbeComponent.h"
#include "Engine/World/Components/PointLightComponent.h"
#include "Engine/World/Components/SkyLightComponent.h"
#include "Engine/World/Components/SpotLightComponent.h"
#include "Engine/World/Components/StaticMeshComponent.h"
#include "Engine/World/Components/SceneComponent.h"
#include "Engine/World/Components/SkyboxComponent.h"

#include "Engine/World/SceneViewport.h"
#include "Engine/World/World.h"

#include "Engine.h"
#include "EngineModule.h"
