[RHI]
RHI.Type = Vulkan
RHI.EnableDebugLayer = true
RHI.EnableValidation = true
RHI.EnableRHIThread = true
RHI.ShaderCompiler.VerboseLogging = false
RHI.ShaderCompiler.Debug = true

[D3D12RHI]
D3D12RHI.EnableDRED = false
D3D12RHI.EnablePIX = false
D3D12RHI.EnableGPUValidation = false
D3D12RHI.BreakOnError = true
D3D12RHI.BreakOnWarning = false

[VulkanRHI]
VulkanRHI.EnableVSync = false
VulkanRHI.BreakOnValidationError = true

[Renderer]
Renderer.DrawRendererInfo = false
; Renderer.Feature.TemporalAA = false
; Renderer.Feature.PrePass = false
; Renderer.Feature.BasePass = false
; Skybox
; Renderer.Feature.Skybox = true
; Renderer.Skybox.ClearBeforeSkybox = true
; Cascaded Shadow Maps
Renderer.CSM.StableCascades = true
Renderer.CSM.AdaptiveSplitRange = true
Renderer.CSM.ShadowPancaking = true
Renderer.CSM.CascadeFallback = true
Renderer.CSM.CascadeSize = 1024
Renderer.CSM.MaxShadowDistance = 1000.0
Renderer.CSM.MaxShadowDistanceFade = 50.0
Renderer.CSM.FilterMode = 1
Renderer.CSM.FilterFunction = 3
Renderer.CSM.NumPoissonDiscSamples = 32
Renderer.CSM.RotateSamples = true
Renderer.CSM.BlendCascades = true
Renderer.CSM.SelectCascadeFromProjection = true
Renderer.CSM.PCF.FilterWorld = 0.05
Renderer.CSM.PCF.MinFilterRadiusTexels = 0.5
Renderer.CSM.TightFrustum = true
Renderer.CSM.TightFrustum.StableExtents = true
Renderer.CSM.TightFrustum.ShrinkLerp = 0.005
Renderer.CSM.TightFrustum.DepthQuant = 256
Renderer.CSM.CascadeFitAABB = false
; PCSS tuning (only used when Renderer.CSM.FilterMode = 1)
Renderer.CSM.PCSS.RadiusScale = 1.0
Renderer.CSM.PCSS.MinFilterMaxAngularDiameter = 1.5
Renderer.CSM.PCSS.BlockerSearchAngularDiameter = 1.0
Renderer.CSM.PCSS.NumBlockerSamples = 64
Renderer.CSM.PCSS.MaxSearchDistanceWorld = 1.0
Renderer.CSM.PCSS.MaxPenumbraWorld = 6.0
Renderer.CSM.PCSS.BlockerSamplingClump = 4.0
Renderer.CSM.PCSS.BlockerSearchScale = 0.5
Renderer.CSM.EnableSinglePassRendering = true
Renderer.CSM.EnableGeometryShaderInstancing = false
; Renderer.CSM.CascadeSize = 4096
; Renderer.CSM.PCSS.MaxSearchDistanceWorld = 0.0
; Renderer.CSM.PCSS.MaxPenumbraWorld = 0.0
; Renderer.CSM.PCSS.BlockerSamplingClump = 0.0
; Renderer.CSM.PCSS.BlockerSearchScale = 1.0
; Shadows
; Renderer.Feature.Shadows = false
; Renderer.Feature.PointLightShadows = true
; Renderer.Feature.SunShadows = false
Renderer.Shadows.PointLightShadowMapSize = 512
; PointLights
Renderer.PointLights.EnableSinglePassRendering = true
Renderer.PointLights.EnableGeometryShaderInstancing = false
; SSAO
; Renderer.Feature.SSAO = false

[ImGui]
; ImGui.UseWindowDPIScale = true
; ImGui.ShowDemoWindow = true
; ImGui.EnableImGuiDelegates = false

[Engine]
Engine.AssetManager.EnableAssetConversion = false
Engine.ViewportWidth = 2560
Engine.ViewportHeight = 1440
; Engine.ViewportWidth = 3840
; Engine.ViewportHeight = 2160
; Engine.ViewportWidth = 1920
; Engine.ViewportHeight = 1080

[Editor]
; Editor.Pick.Debug = true
; Editor.Pick.SearchRadius = 16
