[RHI]
RHI.Type = D3D12
RHI.EnableDebugLayer = true
RHI.EnableValidation = true
RHI.EnableRHIThread = true
RHI.ShaderCompiler.VerboseLogging = false
RHI.ShaderCompiler.Debug = true
RHI.ShaderCompiler.DebugOutputGLSL = false

[D3D12RHI]
D3D12RHI.EnableDRED = false
D3D12RHI.EnablePIX = false
D3D12RHI.EnableGPUValidation = false
D3D12RHI.BreakOnError = true
D3D12RHI.BreakOnWarning = false
D3D12RHI.EnableResidencyTracking = true
D3D12RHI.EnableTightAlignment = true
; D3D12RHI.ResidencyDebugBudgetMB = 512

[VulkanRHI]
VulkanRHI.EnableVSync = false
VulkanRHI.BreakOnValidationError = true

[Renderer]
Renderer.DrawRendererInfo = false
Renderer.DrawSettingsWindow = false
; Renderer.Feature.TemporalAA = false
; Renderer.Feature.PrePass = false
; Renderer.Feature.BasePass = false
; Skybox
; Renderer.Feature.Skybox = true
; Renderer.Skybox.ClearBeforeSkybox = true
; Cascaded Shadow Maps
; Renderer.PrePass.DepthReduce = false
Renderer.CSM.FilterMode = 1
Renderer.CSM.FilterFunction = 1
Renderer.CSM.FilterSize = 256
Renderer.CSM.BlendCascades = true
Renderer.CSM.SelectCascadeFromProjection = true
Renderer.CSM.CascadeSize = 2048
Renderer.CSM.EnableGeometryShaderInstancing = false
Renderer.CSM.EnableViewInstancing = false
Renderer.CSM.EnableSinglePassRendering = true
; Shadows
; Renderer.Feature.Shadows = false
; Renderer.Feature.PointLightShadows = true
; Renderer.Feature.ShadowMask = false
; Renderer.Feature.SunShadows = false
Renderer.Shadows.PointLightShadowMapSize = 512
; PointLights
Renderer.PointLights.EnableGeometryShaderInstancing = false
Renderer.PointLights.EnableSinglePassRendering = true
; SSAO
; Renderer.Feature.SSAO = false

[ImGui]
; ImGui.UseWindowDPIScale = true
; ImGui.ShowDemoWindow = true
; ImGui.EnableImGuiDelegates = false

[Engine]
Engine.AssetManager.EnableAssetConversion = false
Engine.ViewportWidth = 2560
Engine.ViewportHeight = 1440
; Engine.ViewportWidth = 3840
; Engine.ViewportHeight = 2160
; Engine.ViewportWidth = 1920
; Engine.ViewportHeight = 1080

[Editor]
; Editor.Pick.Debug = true
; Editor.Pick.SearchRadius = 16
