#pragma once

bool ButtonControl_Test();
bool GhostButtonControl_Test();
bool CheckBoxControl_Test();
bool SliderControl_Test();
bool SpinBoxControl_Test();
bool ScrollBarControl_Test();
bool ScrollBoxScrollBar_Test();
bool ScrollBarAutoHide_Test();
bool OverlayControl_Test();
bool SpacerSeparatorControl_Test();
bool ExpanderControl_Test();
bool ExpanderAnimation_Test();
bool IndexedPathMove_Test();
bool SearchBoxControl_Test();
bool SearchBoxClearStyle_Test();
bool NumericEntryControl_Test();
bool ProgressBarControl_Test();
bool HistogramControl_Test();
