#pragma once
#include "D3D12RHI/D3D12Configuration.h"

#define D3D12_MAX_ROOT_PARAMETERS (64)
#define D3D12_MAX_SHADER_PARAMETERS (16)
#define D3D12_MAX_HIT_GROUPS (512)
#define D3D12_MAX_DESCRIPTOR_RANGES (64)
#define D3D12_MAX_DESCRIPTOR_RANGE_SIZE (256)
#define D3D12_MAX_32BIT_SHADER_CONSTANTS_COUNT (32)
#define D3D12_MAX_ROOT_PARAMETER_COST (64)
#define D3D12_MAX_VERTEX_BUFFER_SLOTS (D3D12_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT)                           // 32
#define D3D12_MAX_RENDER_TARGET_COUNT (D3D12_SIMULTANEOUS_RENDER_TARGET_COUNT)                              // 8
#define D3D12_MAX_VIEWPORT_AND_SCISSORRECT_COUNT (D3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE) // 16
#define D3D12_MAX_RESOURCE_ONLINE_DESCRIPTOR_COUNT (D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1)   // 1000000
#define D3D12_MAX_SAMPLER_ONLINE_DESCRIPTOR_COUNT (D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE)              // 2048
#define D3D12_MAX_OFFLINE_DESCRIPTOR_COUNT (2048)

#define D3D12_NUM_BACK_BUFFERS (3)

#define D3D12_PIPELINE_STATE_STREAM_ALIGNMENT (sizeof(void*))
#define D3D12_DEFAULT_QUERY_COUNT (65536)

#define D3D12_DEFAULT_ONLINE_RESOURCE_DESCRIPTOR_COUNT (D3D12_MAX_RESOURCE_ONLINE_DESCRIPTOR_COUNT)
#define D3D12_DEFAULT_ONLINE_SAMPLER_DESCRIPTOR_COUNT (D3D12_MAX_SAMPLER_ONLINE_DESCRIPTOR_COUNT)

#define D3D12_TARGET_ROOT_SIGNATURE_DWORD_COST (13)

#define D3D12_CACHED_DESCRIPTORS_COUNT (64)
#define D3D12_CACHED_DESCRIPTORS_NUM_STAGES (EShaderVisibility::Count)

#define D3D12_DEFAULT_CONSTANT_BUFFER_COUNT (64)
#define D3D12_DEFAULT_SHADER_RESOURCE_VIEW_COUNT (64)
#define D3D12_DEFAULT_UNORDERED_ACCESS_VIEW_COUNT (64)
#define D3D12_DEFAULT_SAMPLER_STATE_COUNT (64)

#define D3D12_MAX_LOCAL_ROOT_DESCRIPTORS (16)
#define D3D12_MAX_LOCAL_RECORD_ENTRIES (4)
#define D3D12_MAX_LOCAL_TABLE_DESCRIPTORS (16)

// ------------------------------------------------------------------------------------------------
// Space: | Usage:
// 0      | Standard
// 1      | Constants
// 2      | Ray Tracing Local
// ------------------------------------------------------------------------------------------------

#define D3D12_SHADER_REGISTER_SPACE_32BIT_CONSTANTS (1)
#define D3D12_SHADER_REGISTER_SPACE_RAY_TRACING_LOCAL (2)

static constexpr UINT D3D12_DEFAULT_MULTISAMPLE_QUALITY = 0;