#pragma once
#include "Core/Core.h"

#ifndef D3D12_ENABLE_PIX_MARKERS
    #define D3D12_ENABLE_PIX_MARKERS (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_CRASH_MARKERS
    #define D3D12_ENABLE_CRASH_MARKERS (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_GPU_VALIDATION
    #define D3D12_ENABLE_GPU_VALIDATION (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_MEMORY_LOGGING
    #define D3D12_ENABLE_MEMORY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_LOGGING
    #define D3D12_ENABLE_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_DEVICE_LOST_CHECK
    #define D3D12_ENABLE_DEVICE_LOST_CHECK (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_BINDING_DEBUG_NAMES
    #define D3D12_ENABLE_BINDING_DEBUG_NAMES (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_BINDING_VALIDATION
    #define D3D12_ENABLE_BINDING_VALIDATION (0)
#endif

#ifndef D3D12_ENABLE_RESOURCE_STATE_VALIDATION
    #define D3D12_ENABLE_RESOURCE_STATE_VALIDATION (0)
#endif

#ifndef D3D12_ENABLE_RESIDENCY_LOGGING
    #define D3D12_ENABLE_RESIDENCY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_BREAK_ON_HASH_COLLISION
    #if DEBUG_BUILD
        #define D3D12_BREAK_ON_HASH_COLLISION (1)
    #else
        #define D3D12_BREAK_ON_HASH_COLLISION (0)
    #endif
#endif
