#pragma once
#include "Core/Core.h"

#define D3D12_MAX_ROOT_PARAMETERS                  (64)
#define D3D12_MAX_SHADER_PARAMETERS                (16)
#define D3D12_MAX_HIT_GROUPS                       (512)
#define D3D12_MAX_DESCRIPTOR_RANGES                (64)
#define D3D12_MAX_DESCRIPTOR_RANGE_SIZE            (256)
#define D3D12_MAX_32BIT_SHADER_CONSTANTS_COUNT     (32)
#define D3D12_MAX_VERTEX_BUFFER_SLOTS              (D3D12_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT)            // 32
#define D3D12_MAX_RENDER_TARGET_COUNT              (D3D12_SIMULTANEOUS_RENDER_TARGET_COUNT)               // 8
#define D3D12_MAX_RESOURCE_ONLINE_DESCRIPTOR_COUNT (D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1) // 1000000
#define D3D12_MAX_SAMPLER_ONLINE_DESCRIPTOR_COUNT  (D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE)           // 2048
#define D3D12_MAX_OFFLINE_DESCRIPTOR_COUNT         (2048)

#define D3D12_NUM_BACK_BUFFERS     (3)

#define D3D12_DEFAULT_QUERY_COUNT  (128)

#define D3D12_DEFAULT_ONLINE_RESOURCE_DESCRIPTOR_COUNT  (D3D12_MAX_RESOURCE_ONLINE_DESCRIPTOR_COUNT)
#define D3D12_DEFAULT_ONLINE_SAMPLER_DESCRIPTOR_COUNT   (D3D12_MAX_SAMPLER_ONLINE_DESCRIPTOR_COUNT)

#define D3D12_CACHED_DESCRIPTORS_COUNT                  (16)
#define D3D12_CACHED_DESCRIPTORS_NUM_STAGES             (ShaderVisibility_Count)

#define D3D12_DEFAULT_CONSTANT_BUFFER_COUNT             (8)
#define D3D12_DEFAULT_SHADER_RESOURCE_VIEW_COUNT        (16)
#define D3D12_DEFAULT_UNORDERED_ACCESS_VIEW_COUNT       (8)
#define D3D12_DEFAULT_SAMPLER_STATE_COUNT               (8)

#define D3D12_DEFAULT_LOCAL_CONSTANT_BUFFER_COUNT       (4)
#define D3D12_DEFAULT_LOCAL_SHADER_RESOURCE_VIEW_COUNT  (8)
#define D3D12_DEFAULT_LOCAL_UNORDERED_ACCESS_VIEW_COUNT (4)
#define D3D12_DEFAULT_LOCAL_SAMPLER_STATE_COUNT         (4)

// Space: | Usage:
// 0      | Standard
// 1      | Constants
// 2      | RT Local

#define D3D12_SHADER_REGISTER_SPACE_32BIT_CONSTANTS (1)
#define D3D12_SHADER_REGISTER_SPACE_RT_LOCAL        (2)