#pragma once
#include "Core/Core.h"
#include <d3d12.h>

#ifndef D3D12_ENABLE_PIX_MARKERS
    #define D3D12_ENABLE_PIX_MARKERS (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_CRASH_MARKERS
    #define D3D12_ENABLE_CRASH_MARKERS (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_GPU_VALIDATION
    #define D3D12_ENABLE_GPU_VALIDATION (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_MEMORY_LOGGING
    #define D3D12_ENABLE_MEMORY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_LOGGING
    #define D3D12_ENABLE_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_DEVICE_LOST_CHECK
    #define D3D12_ENABLE_DEVICE_LOST_CHECK (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_BINDING_DEBUG_NAMES
    #define D3D12_ENABLE_BINDING_DEBUG_NAMES (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_BINDING_VALIDATION
    #define D3D12_ENABLE_BINDING_VALIDATION (0)
#endif

#ifndef D3D12_ENABLE_RESOURCE_STATE_VALIDATION
    #define D3D12_ENABLE_RESOURCE_STATE_VALIDATION (0)
#endif

#ifndef D3D12_ENABLE_RESIDENCY_LOGGING
    #define D3D12_ENABLE_RESIDENCY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_PIPELINE_STATE_STREAM
    #define D3D12_ENABLE_PIPELINE_STATE_STREAM (1)
#endif

#ifndef D3D12_ENABLE_VERSIONED_ROOT_SIGNATURES
    #define D3D12_ENABLE_VERSIONED_ROOT_SIGNATURES (1)
#endif

#ifndef D3D12_ENABLE_DEBUG_MESSAGE_CALLBACK
    #define D3D12_ENABLE_DEBUG_MESSAGE_CALLBACK (!RELEASE_BUILD)
#endif

#ifndef D3D12_ENABLE_STATIC_DESCRIPTORS
    #define D3D12_ENABLE_STATIC_DESCRIPTORS (0)
#endif

// Only enable the static descriptors if we have versioned root-signatures
#if D3D12_ENABLE_STATIC_DESCRIPTORS && !D3D12_ENABLE_VERSIONED_ROOT_SIGNATURES
    #undef  D3D12_ENABLE_STATIC_DESCRIPTORS
    #define D3D12_ENABLE_STATIC_DESCRIPTORS (0)
#endif

#ifndef D3D12_BREAK_ON_HASH_COLLISION
    #if DEBUG_BUILD
        #define D3D12_BREAK_ON_HASH_COLLISION (1)
    #else
        #define D3D12_BREAK_ON_HASH_COLLISION (0)
    #endif
#endif

#if D3D12_ENABLE_VERSIONED_ROOT_SIGNATURES && defined(__ID3D12VersionedRootSignatureDeserializer_INTERFACE_DEFINED__)
    #define D3D12_USE_VERSIONED_ROOT_SIGNATURES (1)
#else
    #define D3D12_USE_VERSIONED_ROOT_SIGNATURES (0)
#endif

#if D3D12_ENABLE_DEBUG_MESSAGE_CALLBACK && defined(__ID3D12InfoQueue1_INTERFACE_DEFINED__)
    #define D3D12_USE_DEBUG_MESSAGE_CALLBACK (1)
#else
    #define D3D12_USE_DEBUG_MESSAGE_CALLBACK (0)
#endif
