#pragma once
#include "Core/Stats/Stats.h"

STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_Viewports);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_DrawLists);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_DrawCalls);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_Vertices);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_Triangles);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_UniqueTextures);

STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_UploadedGeometry);
STAT_DECLARE_EXTERN(IMGUIPLUGIN_API, STAT_ImGui_GeometryBuffers);
