-- Support for shaders that are compiled into C headers as a build step instead of being loaded from
-- disk at runtime. The generated headers are checked in, and each rule only reruns when its source
-- is newer than its outputs, so an ordinary build leaves them untouched.

function ResolveDxcExecutable(FallbackFolder)
    local Executable = IsPlatformWindows() and 'dxc.exe' or 'dxc'
    local DxcPath    = CreateExternalThirdpartyPath(JoinPath('DXC/bin', Executable))

    if not os.isfile(DxcPath) and FallbackFolder then
        DxcPath = JoinPath(FallbackFolder, Executable)
    end

    return DxcPath
end

function GetSpirvShaderArguments(Profile, EntryPoint)
    return table.concat({
        '-T ' .. Profile,
        '-E ' .. (EntryPoint or 'Main'),
        '-HV 2021',
        '-WX',
        '-O3',
        '-all-resources-bound',
        '-spirv',
        '-fspv-target-env=vulkan1.2',
        '-fspv-reduce-load-size',
        '-fvk-use-dx-layout',
    }, ' ')
end

-- Compiler:     Path to the shader compiler, see ResolveDxcExecutable
-- Source:       Shader path relative to the module
-- OutputFolder: Folder for the generated headers relative to the module, defaults to 'Generated'
-- Arguments:    Compiler arguments shared by every permutation, see GetSpirvShaderArguments
-- SymbolPrefix: Prefix of the generated byte array, the permutation name is appended to it
-- Permutations: Ordered array of { Name, Defines }, where Defines is an array of 'NAME=VALUE'
function AddGeneratedShaderHeaderRule(Module, Options)
    local RequiredOptions = { 'Compiler', 'Source', 'Arguments', 'SymbolPrefix', 'Permutations' }
    for _, OptionName in ipairs(RequiredOptions) do
        if not Options[OptionName] then
            LogError("AddGeneratedShaderHeaderRule: '%s' is required", OptionName)
            return
        end
    end

    local RelativeSource = Options.Source:gsub('\\', '/')
    local SourcePath     = JoinPath(Module.GetPath(), RelativeSource)
    local OutputFolder   = JoinPath(Module.GetPath(), Options.OutputFolder or 'Generated')
    local ShaderName     = path.getbasename(RelativeSource)
    local Commands       = {}
    local Outputs        = {}

    for _, Permutation in ipairs(Options.Permutations) do
        local OutputHeader = JoinPath(OutputFolder, ('%s_%s.h'):format(ShaderName, Permutation.Name))

        local Defines = ''
        for _, Define in ipairs(Permutation.Defines or {}) do
            Defines = Defines .. ' -D ' .. Define
        end

        table.insert(Commands, ('"%s" %s%s -Fh "%s" -Vn %s%s "%s"'):format(
            Options.Compiler, Options.Arguments, Defines, OutputHeader,
            Options.SymbolPrefix, Permutation.Name, SourcePath))

        table.insert(Outputs, OutputHeader)
    end

    Module.RemoveExcludeFiles({
        '**' .. path.getextension(RelativeSource),
    })
    
    Module.AddCustomBuildRules({
        {
            FilePattern = '**/' .. RelativeSource,
            Message     = 'Compiling internal shader %{file.name}',
            Commands    = Commands,
            Outputs     = Outputs,
        },
    })
end
