-- Engine version and build-stamp generation

local gEngineName         = "DXR-Engine"
local gEngineVersionMajor = 0
local gEngineVersionMinor = 1
local gEngineVersionPatch = 0

-- Location of the generated header. Gitignored, so it only exists after a generation.
local function GetBuildStampFolder()
    return JoinPath(GetRuntimeFolderPath(), "Core/Generated")
end

local function GetBuildStampPath()
    return JoinPath(GetBuildStampFolder(), "BuildStamp.h")
end

-- Run a git command in the engine folder and return its trimmed output.
local function RunGitCommand(Arguments)
    local NullDevice = (os.host() == "windows") and "NUL" or "/dev/null"
    local Command    = string.format('git -C "%s" %s 2>%s', GetEnginePath(), Arguments, NullDevice)

    local Output = os.outputof(Command)
    if not Output then
        return nil
    end

    Output = Output:gsub("^%s*(.-)%s*$", "%1")
    if Output == "" then
        return nil
    end

    return Output
end

local function BuildStampContent()
    local Branch        = RunGitCommand("rev-parse --abbrev-ref HEAD") or "Unknown"
    local Commit        = RunGitCommand("rev-parse --short=12 HEAD") or "Unknown"
    local CommitDate    = RunGitCommand("log -1 --format=%cI") or "Unknown"
    local bIsDirty      = RunGitCommand("status --porcelain --untracked-files=no -- Runtime Sandbox Tests Tools SetupScripts") ~= nil
    local VersionString = string.format("%d.%d.%d", gEngineVersionMajor, gEngineVersionMinor, gEngineVersionPatch)

    local Lines = {
        "// Generated by premake, do not edit. See SetupScripts/Scripts/BuildTool_Version.lua",
        "#pragma once",
        "",
        '#define ENGINE_NAME              "' .. gEngineName .. '"',
        "#define ENGINE_VERSION_MAJOR     (" .. gEngineVersionMajor .. ")",
        "#define ENGINE_VERSION_MINOR     (" .. gEngineVersionMinor .. ")",
        "#define ENGINE_VERSION_PATCH     (" .. gEngineVersionPatch .. ")",
        '#define ENGINE_VERSION_STRING    "' .. VersionString .. '"',
        "",
        '#define BUILD_BRANCH             "' .. Branch .. '"',
        '#define BUILD_COMMIT             "' .. Commit .. '"',
        '#define BUILD_COMMIT_DATE        "' .. CommitDate .. '"',
        "#define BUILD_WORKING_TREE_DIRTY (" .. (bIsDirty and "1" or "0") .. ")",
        "",
    }

    return table.concat(Lines, "\n")
end

-- Generate the build-stamp header consumed by Core/Misc/BuildInfo.cpp.
function GenerateBuildStampHeader()
    local StampFolder = GetBuildStampFolder()
    local StampPath   = GetBuildStampPath()
    local Content     = BuildStampContent()

    -- Avoid touching the mtime when nothing changed, since that would recompile BuildInfo.cpp on every generation.
    local ExistingFile = io.open(StampPath, "r")
    if ExistingFile then
        local ExistingContent = ExistingFile:read("*a")
        ExistingFile:close()

        if ExistingContent == Content then
            LogInfo("Build stamp '%s' is up to date", StampPath)
            return
        end
    end

    if not os.isdir(StampFolder) then
        local bCreated, CreateError = os.mkdir(StampFolder)
        if not bCreated then
            LogError("Failed to create folder '%s' (%s)", StampFolder, tostring(CreateError))
            return
        end
    end

    local File, OpenError = io.open(StampPath, "w")
    if not File then
        LogError("Failed to write '%s' (%s)", StampPath, tostring(OpenError))
        return
    end

    File:write(Content)
    File:close()

    LogInfo("Generated build stamp '%s'", StampPath)
end
