include "BuildTool.lua"
include "BuildTool_Target.lua"

-- Name of the workspace being generated
local gWorkspaceName = ""

function GetWorkspaceName()
    return gWorkspaceName
end

function SetWorkspaceName(WorkspaceName)
    gWorkspaceName = WorkspaceName
end

-- All the targets in the workspace (names only)
local gTargets = {}

-- Retrieve a target name that has been added to the workspace (returns the name or nil)
function GetTarget(InTargetName)
    if not InTargetName then
        return nil
    end
    
    for _, TargetName in ipairs(gTargets) do
        if TargetName == InTargetName then
            return TargetName
        end
    end

    return nil
end

-- Returns true if a target name already exists
function IsTarget(InTargetName)
    return GetTarget(InTargetName) ~= nil
end

-- Add a target to the workspace (names only)
function AddTarget(TargetName)
    if type(TargetName) ~= "string" or TargetName == "" then
        LogError("AddTarget: invalid target name")
        return
    end

    if IsTarget(TargetName) then
        LogWarning("Target '%s' already added. Skipping ..", TargetName)
        return
    end

    table.insert(gTargets, TargetName)
end

-- Name of the current target being processed
local gCurrentTargetName = ""

-- Retrieve the current target name
function GetCurrentTargetName()
    return gCurrentTargetName
end

-- Global defines for the whole workspace
local gGlobalDefines = {}

-- Helper function for adding defines
function AddGlobalDefines(InDefine)
    AddUniqueElements(InDefine, gGlobalDefines)
end

-- Projects that should have projects generated
local gProjectRules = {}

-- Adding a rule that should be included as a project in the workspace
function AddProjectRule(InRule)
    table.insert(gProjectRules, InRule)
end

-- Check if a project with a given name was added
local function HasProjectRule(ProjectName)
    for _, Rule in ipairs(gProjectRules) do
        if Rule and Rule.Name == ProjectName then
            return true
        end
    end

    return false
end

-- Name of the project that should be set as startup project
local gStartProjectName = ""

-- The different types of targets that exists within the workspace, used to create different configurations
local gUsedTargetTypes    = {}
local gUsedTargetTypesSet = {}

local gValidTargetTypes = {
    [ETargetType.Game]    = true,
    [ETargetType.Editor]  = true,
    [ETargetType.Program] = true,
}

local function AddTargetType(TargetType)
    if not gValidTargetTypes[TargetType] then
        return false
    end

    if gUsedTargetTypesSet[TargetType] then
        return false
    end

    gUsedTargetTypesSet[TargetType] = true
    table.insert(gUsedTargetTypes, TargetType)
    return true
end

-- Configurations for this workspace
local gConfigurations = { }

-- Target types contribute overlapping sets of configurations, so a workspace mixing
-- Game and Program targets would otherwise list 'Debug' twice.
local function AddConfiguration(ConfigName)
    for i = 1, #gConfigurations do
        if gConfigurations[i] == ConfigName then
            return
        end
    end

    table.insert(gConfigurations, ConfigName)
end

-- Premake treats the first configuration as the default: defaultConfigurationName in the
-- Xcode projects and the initially selected configuration in the Visual Studio solution.
local gPreferredConfiguration = "Development Editor"

-- MSBuild properties that Premake cannot express, written next to the generated projects
local gDirectoryBuildPropsContent =
[[<Project>
  <PropertyGroup>
    <!-- Generated by the build tool -->
    <VcpkgEnabled>false</VcpkgEnabled>
    <VcpkgApplocalDeps>false</VcpkgApplocalDeps>
    <NMakeCleanCommandLine>rem Nothing to clean</NMakeCleanCommandLine>
  </PropertyGroup>
</Project>
]]

-- MSBuild imports the closest Directory.Build.props found when walking up from each project file,
-- so placing it in the solution folder covers every generated project including the thirdparties
local function GenerateDirectoryBuildProps()
    if not BuildWithVisualStudio() then
        return
    end

    local SolutionLocation = GetSolutionsFolderPath()
    if not os.isdir(SolutionLocation) then
        local bCreated, CreateError = os.mkdir(SolutionLocation)
        if not bCreated then
            LogError("Failed to create folder '%s' (%s)", SolutionLocation, tostring(CreateError))
            return
        end
    end

    local FilePath = JoinPath(SolutionLocation, "Directory.Build.props")

    local File, OpenError = io.open(FilePath, "w")
    if not File then
        LogError("Failed to write '%s' (%s)", FilePath, tostring(OpenError))
        return
    end

    File:write(gDirectoryBuildPropsContent)
    File:close()

    LogInfo("Generated MSBuild properties '%s'", FilePath)
end

-- Solution generation
function GenerateSolutionFiles()

    -- Log the start of the generation
    LogInfo("--- Generating Solution Files for Workspace '%s' ---", GetWorkspaceName())

    -- Set the name of the workspace
    workspace(GetWorkspaceName())

    -- Set location of the generated solution file
    local SolutionLocation = GetSolutionsFolderPath()
    location(SolutionLocation)

    LogInfo("Generated solution location '%s'", SolutionLocation)

    GenerateDirectoryBuildProps()

    -- Platforms
    platforms({
        GetArchitecturePlatformName()
    })

    -- Configurations
    configurations(gConfigurations)

    -- Includes
    local RuntimeFolderPathLocal = GetRuntimeFolderPath()
    includedirs({
        RuntimeFolderPathLocal
    })

    -- Workspace defines
    LogInfo("--- Workspace Defines (Num Defines=%d) ---", #gGlobalDefines)
    if #gGlobalDefines > 0 then
        PrintTable("  Using Define '%s'", gGlobalDefines)
    else
        LogInfo("")
    end

    defines(gGlobalDefines)

    -- Debug configs
    filter { "configurations:*Debug*" }
        symbols "On"
        runtime "Debug"
        defines {
            "_DEBUG",
            "DEBUG",
            "DEBUG_BUILD=(1)"
        }
    filter {}

    -- Development configs
    filter { "configurations:*Development*" }
        symbols "On"
        runtime "Release"
        defines {
            "NDEBUG",
            "DEVELOPMENT_BUILD=(1)"
        }
    filter {}

    -- Release configs
    filter { "configurations:*Release*" }
        symbols "Off"
        runtime "Release"
        defines { 
            "NDEBUG",
            "RELEASE_BUILD=(1)"
        }
    filter {}

    -- Editor configs
    filter { "configurations:*Editor*" }
        defines { 
            "EDITOR_BUILD=(1)",
        }
    filter {}

    -- Architecture for all projects
    architecture(GetPremakeArchitecture())

    -- Static vs dynamic CRT (MSVC only
    filter { "action:vs*", "configurations:*Monolithic*" }
        staticruntime "On"  -- /MT(d)
    filter {}

    filter { "action:vs*", "configurations:not *Monolithic*" }
        staticruntime "Off" -- /MD(d)
    filter {}

    -- Startup project name
    LogInfo("StartProject = '%s'", gStartProjectName)
    startproject(gStartProjectName)

    -- Generate project files for all the rules that have been added
    LogInfo("--- Generating module and target project files ---")
    for _, CurrentRule in ipairs(gProjectRules) do
        CurrentRule.GenerateProject()
    end
end

-- Decide startup project based on what was actually generated
local function ComputeStartProjectName()
    if #gTargets == 0 then
        gStartProjectName = ""
        return
    end

    local FirstTarget = gTargets[1]
    local Standalone  = FirstTarget .. "Standalone"
    if HasProjectRule(Standalone) then
        gStartProjectName = Standalone
        return
    end

    -- Default
    gStartProjectName = FirstTarget
end

-- Generate workspace
function GenerateWorkspace()

    -- Logging
    LogInfo("--- Generating Workspace '%s' ---", gWorkspaceName)
    LogInfo("ConfigurationPath = '%s'", GetOutputConfigPath())

    if gTargets == nil then
        LogError("TargetNames cannot be nil")
        return
    end

    if #gTargets < 1 then
        LogError("Workspace must contain at least one target (Current=%d)", #gTargets)
        return
    end

    -- Define the workspace location. We do this with a Unix path since the engine (C++ side) expects this currently.
    local UnixEnginePath = path.translate(GetEnginePath(), "/")
    local EngineLocation = 'ENGINE_LOCATION="' .. UnixEnginePath .. '"'
    AddGlobalDefines({
        EngineLocation
    })

    LogInfo("Engine Path ='%s'", CreateOsPath(GetEnginePath()))
    LogInfo("RuntimeFolderPath = '%s'", CreateOsPath(GetRuntimeFolderPath()))

    -- IDE Defines
    if BuildWithVisualStudio() then
        AddGlobalDefines({
            "IDE_VISUAL_STUDIO",
            "_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING",
            "_CRT_SECURE_NO_WARNINGS",
        })
    end

    -- OS Defines
    if IsPlatformWindows() then
        AddGlobalDefines({
            "PLATFORM_WINDOWS=(1)"
        })
    end
    if IsPlatformMac() then
        AddGlobalDefines({
            "PLATFORM_MACOS=(1)"
        })
    end

    -- Include the target scripts and collect the type of targets we will have in the workspace
    for i = 1, #gTargets do
        local CurrentTargetName = gTargets[i]
        
        local TargetInfo = GetIndexedTargetInfo and GetIndexedTargetInfo(CurrentTargetName) or nil
        if TargetInfo and os.isfile(TargetInfo.ScriptPath) then
            local TargetRule = GetTargetRule and GetTargetRule(CurrentTargetName) or nil
            if not TargetRule then
                LogInfo("Including script '%s' to include target '%s'", CreateOsPath(TargetInfo.ScriptPath), CurrentTargetName)
                include(TargetInfo.ScriptPath)

                TargetRule = GetTargetRule and GetTargetRule(CurrentTargetName) or nil
                if TargetRule then
                    LogInfo("Target '%s' was created in script '%s'", TargetRule.Name or CurrentTargetName, CreateOsPath(TargetInfo.ScriptPath))
                else
                    LogHighlightWarning("Found target '%s' at '%s', but it did not register.", CurrentTargetName, CreateOsPath(TargetInfo.ScriptPath))
                end
            end

            if TargetRule then
                if type(TargetRule.SetPath) == "function" then
                    TargetRule.SetPath(TargetInfo.ScriptDir)
                end

                AddTargetType(TargetRule.TargetType)
            end
        else
            LogError("Target '%s' not found in indexed roots. Ensure it lives under a configured search root.", CurrentTargetName)
        end
    end

    -- Create all configurations that we need
    for i = 1, #gUsedTargetTypes do
        local CurrentTargetType = gUsedTargetTypes[i]
        if CurrentTargetType == ETargetType.Game then
            LogHighlight("Need configuration for ETargetType.Game")

            AddConfiguration("Debug")
            AddConfiguration("Development")
            AddConfiguration("Release")

            if HasPerConfigurationLayouts() then
                AddConfiguration("Debug Monolithic")
                AddConfiguration("Development Monolithic")
                AddConfiguration("Release Monolithic")
            end
        elseif CurrentTargetType == ETargetType.Editor then
            LogHighlight("Need configuration for ETargetType.Editor")

            AddConfiguration("Debug Editor")
            AddConfiguration("Development Editor")
            AddConfiguration("Release Editor")

            if HasPerConfigurationLayouts() then
                AddConfiguration("Debug Editor Monolithic")
                AddConfiguration("Development Editor Monolithic")
                AddConfiguration("Release Editor Monolithic")
            end
        elseif CurrentTargetType == ETargetType.Program then
            LogHighlight("Need configuration for ETargetType.Program")

            -- No Monolithic/Editor variants: a Program is always statically linked and
            -- has no editor build.
            AddConfiguration("Debug")
            AddConfiguration("Development")
            AddConfiguration("Release")
        end
    end

    for i = 1, #gConfigurations do
        if gConfigurations[i] == gPreferredConfiguration then
            table.remove(gConfigurations, i)
            table.insert(gConfigurations, 1, gPreferredConfiguration)
            LogHighlight("Default configuration is '%s'", gPreferredConfiguration)
            break
        end
    end

    for i = 1, #gConfigurations do
        local ConfigName = gConfigurations[i]
        LogHighlight("  Use config '%s'", ConfigName)
    end

    -- Execute targets (include their scripts)
    for i = 1, #gTargets do
        local CurrentTargetName = gTargets[i]

        local CurrentTargetRule = GetTargetRule and GetTargetRule(CurrentTargetName) or nil
        if CurrentTargetRule then
            if not CurrentTargetRule.IsGenerated or not CurrentTargetRule.IsGenerated() then
                LogInfo("Generating Target '%s'.", CurrentTargetName)
                gCurrentTargetName = CurrentTargetName
                CurrentTargetRule.Generate()
            else
                LogHighlightWarning("Target '%s' is already generated in workspace '%s'", CurrentTargetName, GetWorkspaceName())
            end
        else
            LogError("Target '%s' does not exist. Check under a valid search root and that it gets created in the script.", CurrentTargetName)
        end
    end

    gCurrentTargetName = ""

    -- Decide startup project based on what actually got registered
    ComputeStartProjectName()

    -- Generate the actual solution files
    GenerateSolutionFiles()

    LogInfo("--- Finished generating workspace ---")
end
