-- Support for shaders that are compiled into C headers as a build step instead of being loaded from
-- disk at runtime. The generated headers are checked in, and each rule only reruns when its source
-- is newer than its outputs, so an ordinary build leaves them untouched.

function ResolveDxcExecutable(FallbackFolder)
    local Executable = IsPlatformWindows() and 'dxc.exe' or 'dxc'
    local DxcPath    = CreateExternalThirdpartyPath(JoinPath('DXC/bin', Executable))

    if not os.isfile(DxcPath) and FallbackFolder then
        DxcPath = JoinPath(FallbackFolder, Executable)
    end

    return DxcPath
end

function ResolveSpirvCrossExecutable(FallbackFolder)
    local Executable = IsPlatformWindows() and 'spirv-cross.exe' or 'spirv-cross'
    local ToolPath   = CreateExternalThirdpartyPath(JoinPath('SPIRV-Cross/bin', Executable))

    if not os.isfile(ToolPath) and FallbackFolder then
        ToolPath = JoinPath(FallbackFolder, Executable)
    end

    return ToolPath
end

function GetSpirvShaderArguments(Profile, EntryPoint)
    return table.concat({
        '-T ' .. Profile,
        '-E ' .. (EntryPoint or 'Main'),
        '-HV 2021',
        '-WX',
        '-O3',
        '-all-resources-bound',
        '-spirv',
        '-fspv-target-env=vulkan1.2',
        '-fspv-reduce-load-size',
        '-fvk-use-dx-layout',
    }, ' ')
end

-- Compiler:     Path to the shader compiler, see ResolveDxcExecutable
-- Source:       Shader path relative to the module
-- OutputFolder: Folder for the generated headers relative to the module, defaults to 'Generated'
-- Arguments:    Compiler arguments shared by every permutation, see GetSpirvShaderArguments
-- SymbolPrefix: Prefix of the generated byte array, the permutation name is appended to it
-- Permutations: Ordered array of { Name, Defines }, where Defines is an array of 'NAME=VALUE'
function AddGeneratedShaderHeaderRule(Module, Options)
    local RequiredOptions = { 'Compiler', 'Source', 'Arguments', 'SymbolPrefix', 'Permutations' }
    for _, OptionName in ipairs(RequiredOptions) do
        if not Options[OptionName] then
            LogError("AddGeneratedShaderHeaderRule: '%s' is required", OptionName)
            return
        end
    end

    local RelativeSource = Options.Source:gsub('\\', '/')
    local SourcePath     = JoinPath(Module.GetPath(), RelativeSource)
    local OutputFolder   = JoinPath(Module.GetPath(), Options.OutputFolder or 'Generated')
    local ShaderName     = path.getbasename(RelativeSource)
    local Commands       = {}
    local Outputs        = {}

    for _, Permutation in ipairs(Options.Permutations) do
        local OutputHeader = JoinPath(OutputFolder, ('%s_%s.h'):format(ShaderName, Permutation.Name))

        local Defines = ''
        for _, Define in ipairs(Permutation.Defines or {}) do
            Defines = Defines .. ' -D ' .. Define
        end

        table.insert(Commands, ('"%s" %s%s -Fh "%s" -Vn %s%s "%s"'):format(
            Options.Compiler, Options.Arguments, Defines, OutputHeader,
            Options.SymbolPrefix, Permutation.Name, SourcePath))

        table.insert(Outputs, OutputHeader)
    end

    Module.RemoveExcludeFiles({
        '**' .. path.getextension(RelativeSource),
    })
    
    Module.AddCustomBuildRules({
        {
            FilePattern = '**/' .. RelativeSource,
            Message     = 'Compiling internal shader %{file.name}',
            Commands    = Commands,
            Outputs     = Outputs,
        },
    })
end

-- Metal has no bytecode the engine can consume, so the header holds the MSL that spirv-cross emits
-- and the RHI compiles it at startup. The commands are sh, which Metal being macOS only allows.
--
-- Compiler:     Path to dxc, see ResolveDxcExecutable
-- SpirvCross:   Path to spirv-cross, see ResolveSpirvCrossExecutable
-- Source:       Shader path relative to the module
-- OutputFolder: Folder for the generated headers relative to the module, defaults to 'Generated'
-- Arguments:    Compiler arguments shared by every permutation, see GetSpirvShaderArguments
-- MSLVersion:   Metal Shading Language version spirv-cross targets, defaults to 2.3
-- SymbolPrefix: Prefix of the generated byte array, the permutation name is appended to it
-- Permutations: Ordered array of { Name, Defines }, where Defines is an array of 'NAME=VALUE'
function AddGeneratedMSLShaderHeaderRule(Module, Options)
    local RequiredOptions = { 'Compiler', 'SpirvCross', 'Source', 'Arguments', 'SymbolPrefix', 'Permutations' }
    for _, OptionName in ipairs(RequiredOptions) do
        if not Options[OptionName] then
            LogError("AddGeneratedMSLShaderHeaderRule: '%s' is required", OptionName)
            return
        end
    end

    local RelativeSource = Options.Source:gsub('\\', '/')
    local SourcePath     = JoinPath(Module.GetPath(), RelativeSource)
    local OutputFolder   = JoinPath(Module.GetPath(), Options.OutputFolder or 'Generated')
    local ShaderName     = path.getbasename(RelativeSource)
    local MSLVersion     = Options.MSLVersion or '20300'
    local Commands       = {}
    local Outputs        = {}

    for _, Permutation in ipairs(Options.Permutations) do
        local OutputHeader = JoinPath(OutputFolder, ('%s_%s.h'):format(ShaderName, Permutation.Name))
        local Symbol       = Options.SymbolPrefix .. Permutation.Name
        local SpirvFile    = ('${TMPDIR:-/tmp}/%s.spv'):format(Symbol)
        local MSLFile      = ('${TMPDIR:-/tmp}/%s.msl'):format(Symbol)

        local Defines = ''
        for _, Define in ipairs(Permutation.Defines or {}) do
            Defines = Defines .. ' -D ' .. Define
        end

        -- xxd writes the byte list alone when it reads from stdin, so the declaration is echoed
        -- around it and the whole header is assembled without a packing tool.
        local Steps =
        {
            ('"%s" %s%s -Fo "%s" "%s"'):format(Options.Compiler, Options.Arguments, Defines, SpirvFile, SourcePath),
            ('"%s" "%s" --msl --msl-version %s --msl-texture-buffer-native --output "%s"'):format(Options.SpirvCross, SpirvFile, MSLVersion, MSLFile),
            ('echo "const unsigned char %s[] = {" > "%s"'):format(Symbol, OutputHeader),
            ('xxd -i < "%s" >> "%s"'):format(MSLFile, OutputHeader),
            ('echo "};" >> "%s"'):format(OutputHeader),
            ('rm -f "%s" "%s"'):format(SpirvFile, MSLFile),
        }

        table.insert(Commands, table.concat(Steps, ' && '))
        table.insert(Outputs, OutputHeader)
    end

    Module.RemoveExcludeFiles({
        '**' .. path.getextension(RelativeSource),
    })

    Module.AddCustomBuildRules({
        {
            FilePattern = '**/' .. RelativeSource,
            Message     = 'Compiling internal MSL shader %{file.name}',
            Commands    = Commands,
            Outputs     = Outputs,
        },
    })
end
