#pragma once
#include "Core.h"

#if MONOLITHIC_BUILD
#define COREAPPLICATION_API
#else
#if COREAPPLICATION_IMPL
#define COREAPPLICATION_API MODULE_EXPORT
#else
#define COREAPPLICATION_API MODULE_IMPORT
#endif
#endif