#pragma once
#include "Core/Core.h"

#ifndef VULKAN_ENABLE_CRASH_MARKERS
    #define VULKAN_ENABLE_CRASH_MARKERS (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_GPU_VALIDATION
    #define VULKAN_ENABLE_GPU_VALIDATION (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_MEMORY_LOGGING
    #define VULKAN_ENABLE_MEMORY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_LOGGING
    #define VULKAN_ENABLE_LOGGING (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_DEVICE_LOST_CHECK
    #define VULKAN_ENABLE_DEVICE_LOST_CHECK (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_BINDING_DEBUG_NAMES
    #define VULKAN_ENABLE_BINDING_DEBUG_NAMES (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_BINDING_VALIDATION
    #define VULKAN_ENABLE_BINDING_VALIDATION (!RELEASE_BUILD)
#endif

#define VULKAN_MAX_NUM_PUSH_CONSTANTS (32)

#define VULKAN_MAX_VERTEX_BUFFER_SLOTS (32)
#define VULKAN_MAX_RENDER_TARGET_COUNT (8)
#define VULKAN_MAX_VIEWPORT_AND_SCISSORRECT_COUNT (16)

#define VULKAN_DEFAULT_NUM_SAMPLED_IMAGE_DESCRIPTOR_BINDINGS (64)
#define VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS (64)

#define VULKAN_DEFAULT_UNIFORM_BUFFER_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_SHADER_RESOURCE_VIEW_COUNT (VULKAN_DEFAULT_NUM_SAMPLED_IMAGE_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_UNORDERED_ACCESS_VIEW_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_SAMPLER_STATE_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)

#define VULKAN_DEFAULT_BUFFER_NUM_BYTES (65536)
#define VULKAN_DEFAULT_IMAGE_WIDTH_AND_HEIGHT (4)

#define VULKAN_DEFAULT_QUERY_COUNT (128)

// AMD RDNA recommends staying below 13 DWORDs of user data in a PipelineLayout.
// See: https://gpuopen.com/learn/rdna-performance-guide/ (Descriptors section)
#define VULKAN_RECOMMENDED_MAX_USER_DATA_DWORDS (13)
