#pragma once
#include "VulkanRHI/VulkanConfiguration.h"

#define VULKAN_MAX_NUM_PUSH_CONSTANTS (32)

#define VULKAN_MAX_VERTEX_BUFFER_SLOTS (32)
#define VULKAN_MAX_RENDER_TARGET_COUNT (8)
#define VULKAN_MAX_VIEWPORT_AND_SCISSORRECT_COUNT (16)
#define VULKAN_MAX_STREAM_OUTPUT_BUFFER_COUNT (4)

#define VULKAN_DEFAULT_NUM_SAMPLED_IMAGE_DESCRIPTOR_BINDINGS (64)
#define VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS (64)

#define VULKAN_DEFAULT_UNIFORM_BUFFER_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_SHADER_RESOURCE_VIEW_COUNT (VULKAN_DEFAULT_NUM_SAMPLED_IMAGE_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_UNORDERED_ACCESS_VIEW_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)
#define VULKAN_DEFAULT_SAMPLER_STATE_COUNT (VULKAN_DEFAULT_NUM_DESCRIPTOR_BINDINGS)

#define VULKAN_DEFAULT_BUFFER_NUM_BYTES (65536)
#define VULKAN_DEFAULT_IMAGE_WIDTH_AND_HEIGHT (4)

#define VULKAN_DEFAULT_QUERY_COUNT (65536)

// AMD RDNA recommends staying below 13 DWORDs of user data in a PipelineLayout.
// See: https://gpuopen.com/learn/rdna-performance-guide/ (Descriptors section)
#define VULKAN_RECOMMENDED_MAX_USER_DATA_DWORDS (13)

#define VULKAN_BINDLESS_RESOURCE_BINDING (0)
#define VULKAN_BINDLESS_SAMPLER_BINDING (1)
#define VULKAN_BINDLESS_HEAP_MARKER_SET (31)
#define VULKAN_BINDLESS_RUNTIME_SET_INDEX (0)

#define VULKAN_VALIDATION_LAYER_NAME "VK_LAYER_KHRONOS_validation"
