#pragma once
#include "Core/Core.h"
#include "Core/Stats/Stats.h"

#ifndef VULKAN_ENABLE_STATS
    #define VULKAN_ENABLE_STATS (STATS_ENABLED)
#endif

#ifndef VULKAN_ENABLE_CRASH_MARKERS
    #define VULKAN_ENABLE_CRASH_MARKERS (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_GPU_VALIDATION
    #define VULKAN_ENABLE_GPU_VALIDATION (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_MEMORY_LOGGING
    #define VULKAN_ENABLE_MEMORY_LOGGING (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_LOGGING
    #define VULKAN_ENABLE_LOGGING (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_DEVICE_LOST_CHECK
    #define VULKAN_ENABLE_DEVICE_LOST_CHECK (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_DEBUG_NAMES
    #define VULKAN_ENABLE_DEBUG_NAMES (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_BINDING_DEBUG_NAMES
    #define VULKAN_ENABLE_BINDING_DEBUG_NAMES (!RELEASE_BUILD)
#endif

#ifndef VULKAN_ENABLE_BINDING_VALIDATION
    #define VULKAN_ENABLE_BINDING_VALIDATION (0)
#endif

#ifndef VULKAN_ENABLE_DYNAMIC_UNIFORM_BUFFERS
    #define VULKAN_ENABLE_DYNAMIC_UNIFORM_BUFFERS (1)
#endif

#ifndef VULKAN_ENABLE_RESOURCE_STATE_VALIDATION
    #define VULKAN_ENABLE_RESOURCE_STATE_VALIDATION (0)
#endif

#ifndef VULKAN_BUFFER_ALLOCATOR_USE_POOL_ALLOCATOR
    #define VULKAN_BUFFER_ALLOCATOR_USE_POOL_ALLOCATOR (1)
#endif

#ifndef VULKAN_TEXTURE_ALLOCATOR_USE_POOL_ALLOCATOR
    #define VULKAN_TEXTURE_ALLOCATOR_USE_POOL_ALLOCATOR (1)
#endif

#ifndef VULKAN_VALIDATE_NO_NULL_DESCRIPTORS
    #define VULKAN_VALIDATE_NO_NULL_DESCRIPTORS (0)
#endif

#ifndef VULKAN_BREAK_ON_NULL_DESCRIPTORS
    #define VULKAN_BREAK_ON_NULL_DESCRIPTORS (0)
#endif

#ifndef VULKAN_USE_CPU_QUERY_RESOLVE
    #define VULKAN_USE_CPU_QUERY_RESOLVE (1)
#endif

#ifndef VULKAN_USE_DESCRIPTOR_CACHE
    #define VULKAN_USE_DESCRIPTOR_CACHE (0)
#endif

#ifndef VULKAN_LOG_SEMAPHORE_INDEX
    #define VULKAN_LOG_SEMAPHORE_INDEX (0)
#endif

#ifndef VULKAN_REPORT_SWAPCHAIN_ACQUIRE_IMAGE_NON_SUCCESS_RESULT
    #define VULKAN_REPORT_SWAPCHAIN_ACQUIRE_IMAGE_NON_SUCCESS_RESULT (!RELEASE_BUILD)
#endif
